---
title: "'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 7e7d1a1a9025c2d708d7e5027fd9bcbb4270e60b
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 04/09/2019
ms.locfileid: "59320404"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden.
`Exit Try` kann nur innerhalb einer `Try` -Blockanweisung angezeigt werden. Entweder ist die `Exit Try` -Anweisung redundant, oder die `Exit Try` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30393  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie die unnötige `Exit Try` -Anweisung.  
  
2. Verschieben der `Exit Try` Anweisung, um die gewünschte Position im Code.  
  
## <a name="see-also"></a>Siehe auch

- [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
